### ISSUE TITLE
Deprecate ECR repo provided by optional-test-infra

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/testing#1008] opened 2022-06-14 04:24 UTC
As a post item of deprecating optional-test-infra, we'll deprecate all the ECR repos provided by optional-test-infra. 

### Private ECR Repo List

**kubeflow/katib**: `809251082950.dkr.ecr.us-west-2.amazonaws.com/katib/v1beta1/`
* `cert-generator`
* `earlystopping-medianstop`
* `file-metrics-collector`
* `katib-db-manager`
* `suggestion-chocolate`
* `suggestion-darts`
* `suggestion-enas`
* `suggestion-goptuna`
* `suggestion-hyperband`
* `suggestion-hyperopt`
* `suggestion-optuna`
* `suggestion-skopt`
* `tfevent-metrics-collector`
* `trial-darts-cnn-cifar10`
* `trial-enas-cnn-cifar10-cpu`
* `trial-enas-cnn-cifar10-gpu`
* `trial-mxnet-mnist`
* `trial-pytorch-mnist`
* `trial-tf-mnist-with-summaries`

**kserve/kserve:** `809251082950.dkr.ecr.us-west-2.amazonaws.com/kserve/`
* `agent` 
* `aix-explainer`
* `alibi-explainer`
* `art-explainer`
* `batcher `
* `image-transformer`
* `kserve-controller`
* `lgbserver `
* `paddleserver`
* `pmmlserver`
* `pytorchserver`
* `sklearnserver`
* `storage-initializer`
* `xgbserver`

**kubeflow/training** related: `809251082950.dkr.ecr.us-west-2.amazonaws.com/kserve/`
* `pytorch-operator`
* `tf-operator`
* `training-operator`

### Public ECR Repo List
**kubeflow/kubeflow**: `public.ecr.aws/j1r0q0g6/notebooks`
* `access-management`
* `admission-webhook`
* `central-dashboard`
* `jupyter-web-app`
* `notebook-controller`
* `notebook-servers/base`
* `notebook-servers/codeserver`
* `notebook-servers/jupyter`
* `notebook-servers/jupyter-cuda`
* `notebook-servers/jupyter-pytorch-cuda`
* `notebook-servers/jupyter-pytorch-cuda-full`
* `notebook-servers/jupyter-pytorch-full`
* `notebook-servers/jupyter-scipy`
* `notebook-servers/jupyter-tensorflow`
* `notebook-servers/jupyter-tensorflow-cuda`
* `notebook-servers/jupyter-tensorflow-cuda-full`
* `notebook-servers/jupyter-tensorflow-full`
* `notebook-server/rstudio`
* `notebook-server/rstudio-tidyverse`
* `profile-controller`
* `tensorboard-controller`
* `tensorboards-web-app`
* `volumes-web-app`

**kubeflow/training** related: `public.ecr.aws/j1r0q0g6/training`
* `tf-operator`
* `training-operator`

**Comment by johnugeorge** [comment] 2022-06-14 04:50
Training operator uses the ECR repo for last 3 releases ( v1.4.0, v1.3.0, v1.21, v1.1)  https://github.com/kubeflow/training-operator/blob/master/manifests/overlays/kubeflow/kustomization.yaml#L9 

We should not deprecate the public repos for upcoming few releases. Though we will find an alternative solution starting from this release, we have to allow current users to continue using the release manifests.

**Comment by surajkota** [comment] 2022-06-14 20:29
@PatrickXYS we understand the need to deprecate this repositories but we request you to work with us as we figure out the next gen of this infrastructure. Please see details in https://github.com/kubeflow/testing/issues/1006#issuecomment-1153299757.

In the meantime, we will work on funding the account with the needed credits to use these repositories.

**Comment by thesuperzapper** [comment] 2022-06-15 00:53
@PatrickXYS can please you clarify if we can maintain the old ECR public images (even if we don't add new images) so that people's old manifest don't break?

**Comment by PatrickXYS** [comment] 2022-06-27 03:02
I don't think any kubeflow repos are actively using those ECR images for deployment except notebooks WG.

Reason for the above observation: only notebooks ECR image has version tags such as `v1.1`, `v1.2`, etc. 

So the rest of the other repos are no-concern, but notebooks might be a special one. 

--- 

Due to my current situation, I have very limited bandwidth and am slow to respond.

**Comment by thesuperzapper** [comment] 2022-06-29 02:30
I have mirrored all the `public.ecr.aws/j1r0q0g6/notebooks` ones to GitHub Container Registry under `ghcr.io/kubeflow/{IMAGE_NAME}`, for example:
- [`ghcr.io/kubeflow/kubeflow/access-management`](https://ghcr.io/kubeflow/kubeflow/access-management)
- [`ghcr.io/kubeflow/kubeflow/jupyter-web-app`](https://ghcr.io/kubeflow/kubeflow/jupyter-web-app)
- [`ghcr.io/kubeflow/training/tf-operator`](https://ghcr.io/kubeflow/training/tf-operator)
- ...

These are just a one-time backup of the historical tags, but the working groups can feel free to start using these images for new manifests/releases if they like (GitHub actions within the corresponding kubeflow GitHub repo can push to these registries).

---

@surajkota clarified that we are still planning to keep the old ECR `public.ecr.aws/j1r0q0g6/notebooks` image available by migrating the ECR to be owned by a new AWS account.

I can share the python script I used to migrate the ECR images to GHCR (as this migration can be a bit of a nightmare due to ECR lacking the ability to list tags).

**Comment by thesuperzapper** [comment] 2022-07-05 00:33
I have raised https://github.com/kubeflow/kubeflow/issues/6560 about using `ghcr.io/kubeflow/{IMAGE_NAME}` as the default image registry for Kubeflow images (in addition to a DockerHub / ECR mirror).

**Comment by surajkota** [comment] 2022-07-06 00:04
WGs have confirmed that private ECR registries were only used for testing purpose and have not been used in release manifests. Hence, the **private ECR registries** can be deprecated.

As @thesuperzapper commented, I am looking into migrating the public ECR repositories to a new account(with same registry alias) and will post an update here as soon as I have confirmation on the process. Repositories which need to be migrated:

- `public.ecr.aws/j1r0q0g6/notebooks`
- `public.ecr.aws/j1r0q0g6/training`

**Comment by johnugeorge** [comment] 2022-07-19 04:30
@kimwnasptd Given these complications, Should we just just create and track the mapping previous image location-> new image location for earlier releases? (without any extra changes) 
Release 1.4 or earlier doesn't support k8s 1.21+ anyways. There is very less chance of newer installations. In any case, if users run into issues with images, they can override the image name/tag in kustomization file and move forward.

**Comment by surajkota** [comment] 2022-07-19 06:00
@johnugeorge To clarify, the only action required from one of you(anyone from Notebook or training WG) is to create an email address. The repository will stay in the same account as before and there is no impact on user experience. Please help us understand if this looks complicated to you?

Re: **1.5 or earlier** & [as per your comment on June 13](https://github.com/kubeflow/testing/issues/1008#issuecomment-1154706963), we need to consider the users who have not migrated to newer versions of K8s or Kubeflow. It's not only about new installations, the existing installation will also break. For e.g. notebook server images will become unavailable suddenly. I disagree with your proposal to just document it given the effort is to only create an email address and this account will be part of AWS Organization like the other WG accounts. It's similar to how you might have created a dockerhub account for publishing 1.6 images.

**Comment by PatrickXYS** [comment] 2022-07-21 23:15
> If it is not, would you be ok with just freezing that card and getting a new card?

Let's try to avoid this, please try to get a credit card from your team, and provide the card to @andreyvelich, he can help you replace your card with my card. After that, feel free to take any action. I believe my proposal is a better way to move forward.

**Comment by surajkota** [comment] 2022-07-27 00:38
Hi everyone, the credits applied in the account `809251082950` were about to expire end of this week on 07/31. We have completed the steps outlined in the [comment above](https://github.com/kubeflow/testing/issues/1008#issuecomment-1188162838) to ensure Yao's credit card does not get charged for the billing.

This account is now part of the new AWS organization. Yao, I have opened a case with AWS support to remove your credit card since its no longer required.

**Comment by PatrickXYS** [comment] 2022-08-06 16:37
Great, just saw the message. Please keep me updated with the credit card removal stuff since I can't access the AWS account now, which makes me concerned if AWS will be applying bills to my credit card.

**Comment by PatrickXYS** [comment] 2022-08-06 18:56
@surajkota  Could you please help keep me updated with the card removal process, there are still possibilities that billing will be applied to my card but I have no access to the AWS account. 

As I mentioned in the previous comment: 

> Let's try to avoid this, please try to get a credit card from your team, and replace my card with yours with help from @andreyvelich . After that, feel free to take any action. I believe my proposal is a better way to move forward.

Replace the card before taking any action, but seems like it didn't work on the AWS side, could you please expedite the process to resolve my concern?

**Comment by surajkota** [comment] 2022-09-01 17:51
Hi @PatrickXYS, your credit card has been removed from the account. Thanks for your patience

Info for historical purpose: since this was a standalone account before, it is not possible to remove the default payment information. We added the same card as on the management account with help of @kimwnasptd, Amber Graner.

We can close this issue now.
/close

**Closed** 2022-09-01 17:51 UTC
