### ISSUE TITLE
cleanup_ci: delete Argo jobs that's older than 3 days.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/testing#326] opened 2019-03-08 19:16 UTC
Argo UI becomes very slow to load as Argo jobs pile up.
We can expire history older than 3 days.
@jlewi 
@zhenghuiwang

**Comment by jlewi** [comment] 2019-03-08 23:50
Duplicate of #53

**Closed by jlewi** 2019-03-08 23:50 UTC
